version: '3.8'

services:
  mysql:
    image: mysql
    container_name: employee_mysql
    command: --init-file /data/application/init.sql
    hostname: employeedb
    environment:
      - MYSQL_ROOT_PASSWORD=password@123
      - MYSQL_DATABASE=dev
      - MYSQL_USER=user1
      - MYSQL_PASSWORD=secret
    volumes:
      - ./mysql/init.sql:/data/application/init.sql
      - mysqldata:/var/lib/mysql
    ports:
      - "3000:3306"
    networks:
      - employee_network
    restart: on-failure    
  nginx:
    build:
      context: ./nginx
    container_name: nginx
    hostname: nginx
    ports:
        - "80:80" 
    depends_on:
        - employeeservice
    networks:
        - employee_network
  employeeservice:
    build:
      context: ./rest-service
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    container_name: springbootserver
    hostname: employeeService
    networks:
        - employee_network
    depends_on:
      - mysql

volumes:
  mysqldata:

networks:
  employee_network:
